### ISSUE TITLE
Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by Mailaender** [penev92/Oraide.LanguageServer#1]
Issue Type: <b>Bug</b>

Does not work anymore.

Extension version: 0.0.8
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.3.18-150300.59.43-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.35GB (3.93GB free)|
|Process Argv|--trace-deprecation --crash-reporter-id 5f4a7910-728a-4c18-b925-f729910cba57|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
wslgetstarted:30426333
vscop804cf:30404767
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by penev92** [comment]
Thanks for helping identify the issue!
For the record: this was accidentally fixed in `server-v0.0.5c`, intentionally broken again in `server-v0.0.5e` and fixed again in `server-v0.0.5f`. 
It would appear that
> the `stdin` and `stdout` are exclusively used for client-server communication using the LanguageServerProtocol - meaning it's all messages and requests/responses in a very specific format (JSON-ish)
and when the server puts a random (exception string) message in the `stdout` the client doesn't know what to do with it and dies
~I'm going to bet money that's what's happening~
no clue why this isn't an issue for me though -_-

It also apparently works on Windows but breaks on Linux.

Closing as now both the exception leading to the faulty logging and the logging itself have been fixed.
