### ISSUE TITLE
`prepare` script: copy fails on fresh checkout

### ISSUE THREAD

**Issue by letmaik** [penev92/Oraide.LanguageServer#5]
The "prepare" script tries to copy a file, but the target folder on a fresh checkout doesn't exist and hence it fails.

**Comment by penev92** [comment]
Off, fail.
I need to rethink the entire "gitignore it and then add automatic copying" thing because I'm not sure it if will work at all on non-windows the way I have it now.

P.S.: From what I understand from  https://stackoverflow.com/questions/38026117/how-to-use-package-json-scripts-to-copy-files-with-specific-file-extension  I'm going to need an NPM package for copying files?  🤦‍♂️
